# This file was generated by GoReleaser. DO NOT EDIT.
cask "cantool" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/DisplaceTech/Cantool/releases/download/v#{version}/cantool_darwin_amd64.tar.gz"
      sha256 "ad8f1bfbb2d4c7474f01a3a8bcc8afbb02b882db139195d5a7030da4462b8286"
    end
    on_arm do
      url "https://github.com/DisplaceTech/Cantool/releases/download/v#{version}/cantool_darwin_arm64.tar.gz"
      sha256 "a8b8b6544e1d0e5d1da9fca5b679e8e106d4f021f449b8a79d36863a7e25fb1e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DisplaceTech/Cantool/releases/download/v#{version}/cantool_linux_amd64.tar.gz"
      sha256 "190f09171f6199ab41f3a121c0ac1b88148bd681cb81c9f4ae60b06814ac962c"
    end
    on_arm do
      url "https://github.com/DisplaceTech/Cantool/releases/download/v#{version}/cantool_linux_arm64.tar.gz"
      sha256 "1c8f32ae1a5a52ee0df0e320186ba0f94f7bdb3dcade1954c157285459c0292f"
    end
  end

  name "cantool"
  desc "Canton application development CLI"
  homepage "https://github.com/DisplaceTech/Cantool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cantool"

  # No zap stanza required

end
