# This file was generated by GoReleaser. DO NOT EDIT.
cask "cantool" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/DisplaceTech/Cantool/releases/download/v#{version}/Cantool_#{version}_darwin_amd64.tar.gz"
      sha256 "a0b3ae25306e49ef5f34c97162a11caaca8042d915db6556509ea6f7b18f46a6"
    end
    on_arm do
      url "https://github.com/DisplaceTech/Cantool/releases/download/v#{version}/Cantool_#{version}_darwin_arm64.tar.gz"
      sha256 "f5b62567d6b82b2aeed6da6b5ce788205c30a25b54a4a644adaa581a31b2645d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DisplaceTech/Cantool/releases/download/v#{version}/Cantool_#{version}_linux_amd64.tar.gz"
      sha256 "63c18cefe64a43813eb739a715f36b115cbcd0f5b868abe09c30d46ba3f03eda"
    end
    on_arm do
      url "https://github.com/DisplaceTech/Cantool/releases/download/v#{version}/Cantool_#{version}_linux_arm64.tar.gz"
      sha256 "012120a27183eced2374c66f12fb4c87798a83c2b636f42df1dd511e73a0c2a8"
    end
  end

  name "cantool"
  desc "Canton application development CLI"
  homepage "https://github.com/DisplaceTech/Cantool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cantool"

  # No zap stanza required

end
