# This file was generated by GoReleaser. DO NOT EDIT.
cask "cantool" do
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/DisplaceTech/Cantool/releases/download/v#{version}/cantool_darwin_amd64.tar.gz"
      sha256 "eae89abf260605a8e095fd481db683e21ed3f9d66edcfc75cc093d2d1e63a87f"
    end
    on_arm do
      url "https://github.com/DisplaceTech/Cantool/releases/download/v#{version}/cantool_darwin_arm64.tar.gz"
      sha256 "60d497041a3b41852c31b0000dbc0e16666408eb14e14295a59d9d659317c049"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DisplaceTech/Cantool/releases/download/v#{version}/cantool_linux_amd64.tar.gz"
      sha256 "0702308ed8fd19b95d95a4a59169f3f1051770a484e836a9ecf223c860873d88"
    end
    on_arm do
      url "https://github.com/DisplaceTech/Cantool/releases/download/v#{version}/cantool_linux_arm64.tar.gz"
      sha256 "9a529c4504c12941b2c485f577ec38030c086e8ec2a6be4152395220cc2fc243"
    end
  end

  name "cantool"
  desc "Canton application development CLI"
  homepage "https://github.com/DisplaceTech/Cantool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cantool"

  # No zap stanza required

end
