# This file was generated by GoReleaser. DO NOT EDIT.
cask "journal" do
  version "2.2.1"

  on_macos do
    on_intel do
      sha256 "e58b50dd0c8b472216715a05b03855582f9700a93dda85c50e9154e770e5d6f3"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a8c7cf0a73d38366dd99859c9a68e2b84fb7411e52ccfc43e133dce053c674f"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c50da69a1c01ca3a6b66ebf9f33f0cc5965c780126a5b1a769940dfd98b78897"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6b574a2b52e8d9a0f98d9175bd03ed032b708a62928641831be9915c66220ac"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "journal"
  desc "Local-first developer journal with semantic search and AI synthesis"
  homepage "https://displace.tech"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "journal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/journal"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    journal needs a local Ollama for indexing and search:
      1. install Ollama:        https://ollama.com
      2. pull the embed model:  ollama pull qwen3-embedding:4b
      3. verify your setup:     journal doctor

    An ANTHROPIC_API_KEY in your environment is only needed for `journal synth`.
  EOS
end
