# This file was generated by GoReleaser. DO NOT EDIT.
cask "journal" do
  version "2.0.1"

  on_macos do
    on_intel do
      sha256 "f0ce7af0140a53f5fe4646be6c6b8606041b397c14f80b24ecd42328efb0cff2"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1962c94056abe338eaf53f2722ba2d08ef93b211a1b92dee760c4440bd3cb65"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1b7de4e141d7f664d83b2417859e1946360ad293ad95a533df53ab33d61f721a"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8a5b5d15957cb440e9fdb1f2a97abcabd297cf54c2d19e9e612ae9a8537eddb"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "journal"
  desc "Local-first developer journal with semantic search and AI synthesis"
  homepage "https://displace.tech"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "journal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/journal"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    journal needs a local Ollama for indexing and search:
      1. install Ollama:        https://ollama.com
      2. pull the embed model:  ollama pull qwen3-embedding:4b
      3. verify your setup:     journal doctor

    An ANTHROPIC_API_KEY in your environment is only needed for `journal synth`.
  EOS
end
